[package]
name = "pterminal-render"
version.workspace = true
edition.workspace = true

[dependencies]
pterminal-core.workspace = true
wgpu.workspace = true
glyphon.workspace = true
tracing.workspace = true
anyhow.workspace = true
bytemuck = { version = "1", features = ["derive"] }
ahash = "0.8"
